### ISSUE TITLE
Dnn.readNetFromCaffe SIGSEGV if dev mode is disabled

### ISSUE THREAD

**Issue by joes** [quarkiverse/quarkus-opencv#115]
Loading a caffe model using `Dnn.readNetFromCaffe` fails with SIGSEGV when dev mode is disabled.

Reproducer: 

```bash
git clone git@github.com:joes/quarkus-opencv-read-net-from-caffe-bug-repro.git
cd quarkus-opencv-read-net-from-caffe-bug-repro
mvn clean package -Dquarkus.container-image.build=true
docker run -it --rm github.com/joes/quarkus-opencv-read-net-from-caffe-bug-repro:latest
```

Error:

```Starting the Java application using /opt/jboss/container/java/run/run-java.sh ...
INFO exec  java -Djava.util.logging.manager=org.jboss.logmanager.LogManager -XX:+UseParallelGC -XX:MinHeapFreeRatio=10 -XX:MaxHeapFreeRatio=20 -XX:GCTimeRatio=4 -XX:AdaptiveSizePolicyWeight=90 -XX:+ExitOnOutOfMemoryError -cp "." -jar /deployments/quarkus-run.jar 
2023-05-15 09:44:00,294 INFO  [org.acm.AppLifecycleBean] (main) Load caffe models in 'org.acme.AppLifecycleBean'
#
# A fatal error has been detected by the Java Runtime Environment:
#
#  SIGSEGV (0xb) at pc=0x00007f2dea115c64, pid=1, tid=94
#
# JRE version: OpenJDK Runtime Environment (Red_Hat-11.0.17.0.8-2.el8_6) (11.0.17+8) (build 11.0.17+8-LTS)
# Java VM: OpenJDK 64-Bit Server VM (Red_Hat-11.0.17.0.8-2.el8_6) (11.0.17+8-LTS, mixed mode, sharing, tiered, compressed oops, parallel gc, linux-amd64)
# Problematic frame:
# V  [libjvm.so+0x5b4c64]  AccessInternal::PostRuntimeDispatch<CardTableBarrierSet::AccessBarrier<1097844ul, CardTableBarrierSet>, (AccessInternal::BarrierType)2, 1097844ul>::oop_access_barrier(void*)+0x4
#
# Core dump will be written. Default location: /mnt/wslg/dumps/core.%e
#
# An error report file with more information is saved as:
# /deployments/hs_err_pid1.log
#
# If you would like to submit a bug report, please visit:
#   https://bugzilla.redhat.com/enter_bug.cgi?product=Red%20Hat%20Enterprise%20Linux%208&component=java-11-openjdk
#

[error occurred during error reporting (), id 0xb, SIGSEGV (0xb) at pc=0x00007f2deb088ee1]
```

**Comment by gsmet** [comment]
This can be either a bug in the JDK or in the binary part of OpenCV. Maybe try the latest JDK 17 and see how it goes.

**Comment by joes** [comment]
It is interesting though how quarkus’s dev mode is able to resolve the issue.

**Comment by joes** [comment]
The same issue with `openjdk 17.0.7 2023-04-18 LTS`. 

The problem only goes away if I launch in devmode (setting QUARKUS_LAUNCH_DEVMODE=true):

```bash
QUARKUS_LAUNCH_DEVMODE=true java -Dquarkus.http.host=0.0.0.0 -Djava.util.logging.manager=org.jboss.logmanager.LogManager -Djava.library.path=/usr/java/packages/lib -XshowSettings:all -XX:MaxRAMPercentage=50.0 -XX:+UseSerialGC -XX:MinHeapFreeRatio=10 -XX:MaxHeapFreeRatio=20 -XX:GCTimeRatio=4 -XX:AdaptiveSizePolicyWeight=90 -XX:+ExitOnOutOfMemoryError -cp "." -jar /deployments/quarkus-run.jar
```

**Comment by joes** [comment]
Actually it seems that this method behaves differently in dev-mode than in "normal" execution:

```
    protected static String getResourceFilePath(String fileName) throws Exception {
        ClassLoader classLoader = Thread.currentThread().getContextClassLoader();
        URL resource = classLoader.getResource(fileName);
        return resource.toURI().getPath();
    }
```
    
Used by: 

```java
            net = Dnn.readNetFromCaffe(
                    getResourceFilePath("models/pose/coco/pose_deploy_linevec.prototxt")
                );
```

In dev-mode `getResourceFilePath` returns a valid path whereas in 'normal' mode it returns `null`. It was simply this thing that caused the SIGSEGV.

**Comment by gsmet** [comment]
@joes you might be onto something. Can you confirm that you are building a native executable?

If so, you have to add the static files to the native executable. See https://quarkus.io/guides/writing-native-applications-tips#including-resources .

**Comment by joes** [comment]
No, it was not a native executable - it was a mutable-jar in both instances. 

However, the files were prepared to be included in the native resources.

**Comment by gsmet** [comment]
Hmmm, that's odd. I think we need to get to the bottom of it as there might be an issue in our class loaders.

Could you prepare a small reproducer so that I could have a look?

**Comment by gsmet** [comment]
I finally took some time to have a look at this.

I think it all boils down to the fact that you are passing a pass in a jar to a C library that has absolutely no understanding of what a jar is.
In dev mode, the path is actually a path in the filesystem so it all works. Once you switch to a jar, it doesn't.

I'm not exactly sure how you did things with Spring as your repositories are not available anymore.

But I added a small example here: https://github.com/quarkiverse/quarkus-opencv/pull/138/commits/6c0c07a484ac322597b82272f4a0496d71acc4c1 .

You have actually two options:
- store the models outside of the jars and reference them in the filesystem directly
- store the models in the jar but in this case, you will need to read the model in Java. I added an extremely naive implementation but in a real app, you should read the model in chunks if it is large.

I'm closing this. If you can find back your Spring example, I would be curious to have a look at it.

Thanks!
